package valueobject

// SourceType indicates the origin of a finding or signal.
type SourceType string

const (
	// SourceModelFact means the finding comes directly from model data (facts declared in the model).
	SourceModelFact SourceType = "model_fact"
	// SourceAnalyzerFinding means the finding was detected by a structural analyzer.
	SourceAnalyzerFinding SourceType = "analyzer_finding"
	// SourceAIInterpretation means the finding was generated by an AI model.
	SourceAIInterpretation SourceType = "ai_interpretation"
)
